language: R
sudo: false
cache: packages
r_github_packages: hadley/pkgdown, cran/roxygen2
addons:
  apt:
    packages:
      - libmagick++-dev
before_script:
- chmod +x ./_build.sh
- chmod +x ./_deploy.sh
script:
- "./_build.sh"
- "./_deploy.sh"
env:
  global:
    secure: RgN6j1CB7l5xAGGL58/SKZMZ2ymSGWLG/b299KEsNIOttFqB9rlHdQVKRyjPGrTgoEesIzbmfhBi2zwN9Eb1b8sWTFYepdyXVoIJqNLrds9qvLB6a2ukVFycJqjwh4C/GBYPenMC6QVlDd8ZlxFzowAxqMjyjtCvFLkCUcI4lRd+2/TYjK/atVFV8lyJ/cNLD0t5v3OhNA0GjIAuZhV03sw3OHLHMkulcPskg8XZhflOr1M6rfo4lwAwPzbZwEzOaicxVNVyseLBxbTRywrdfYC4SWHQ4Km3J3y5KWiRDYHBfjX0WfGiXUaiTUGnNGC4vGLz6tZibciSnfLxfS6SvG2Sv1bbacFf4csFZar5rpcl0af702zy/XOK/ZORi+vK/HkuQJcj2/gApXwq+xqdIJ/jN55ab/ImHjFtOXJtV4FHdSZSQ+wAjoIprJhEf45eT25ohIvX3Y7GabI3tqxjq6EVTGG55iaF+7qnl41HBDa1bAUAtd9iAgYLwZhmim++zmwOtX+wr2mGk9WnKxaS98UA1CUcUQqEn91v/gaGPo73K2koa74eaNuYZeuoporrz4XxWE7X9yKAh0NzZb7Z8+7W4rWg2wP7yr2JUDIMfoTIPDKoHXgtQetCFdqLn4Ef0za2+eT4W7Q/cTrJU+bgPzfscKV/7rtgIsIQYuDmCfk=
